# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim
WORKDIR /app

# Install OS dependencies for newspaper3k and sumy
RUN apt-get update && apt-get install -y \
    build-essential \
    libxml2-dev \
    libxslt-dev \
    zlib1g-dev && rm -rf /var/lib/apt/lists/*

COPY . .

# Install Python dependencies: include lxml_html_clean for newspaper
RUN pip install --no-cache-dir -r requirements.txt \
    && pip install --no-cache-dir lxml_html_clean

# Default command to start the MCP server
CMD ["python", "app.py"]
