# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim
WORKDIR /app
COPY . /app
RUN pip install --no-cache-dir lxml_html_clean
RUN pip install --no-cache-dir -r requirements.txt
CMD ["python", "app.py"]
